### PR TITLE
feat: add precincts reporting percent override

### PR DESCRIPTION
**Pull request by chriszs**
## Description

This PR adds an override to allow specifying a reporting status for precincts in a specific county. To use, you add `--precinctsReportingPct='{"bacon":0}'`, specifying the county IDs and reporting percents, to the CLI. This sets all the subunits to the same reporting percent, as well as overall result, so the above example will set all subunits in Bacon county to `0` as well as the overall percent for Bacon county itself.

## Jira Ticket

[ELEX-1959](https://arcpublishing.atlassian.net/browse/ELEX-1959)

## Test Steps

```sh
tox
elexclarity 115470 GA --level=precinct --officeID=P --countyName=Bacon --voteCompletionMode=combined --precinctsReportingPct='{"bacon":0}' --filename="tests/fixtures/results/ga_bacon_precincts_11-3.xml"
```

## After

```js
{
  "2020-11-03_GA_G_P_bacon": {
    "id": "2020-11-03_GA_G_P_bacon",
    "source": "clarity",
    "precinctsReportingPct": 0,
    "counts": {
      "2020-11-03_GA_G_P_bacon_donald_j_trump_i_rep": 4018,
      "2020-11-03_GA_G_P_bacon_joseph_r_biden_dem": 625,
      "2020-11-03_GA_G_P_bacon_jo_jorgensen_lib": 25
    },
    "office": "P",
    "lastUpdated": "2020-11-05T16:39:44Z",
    "subunits": {
      "bacon_douglas": {
        "id": "bacon_douglas",
        "counts": {
          "2020-11-03_GA_G_P_bacon_donald_j_trump_i_rep": 4018,
          "2020-11-03_GA_G_P_bacon_joseph_r_biden_dem": 625,
          "2020-11-03_GA_G_P_bacon_jo_jorgensen_lib": 25
        },
        // ...
        "precinctsReportingPct": 0
      }
    }
  }
}
```

## Before

```js
{
  "2020-11-03_GA_G_P_bacon": {
    "id": "2020-11-03_GA_G_P_bacon",
    "source": "clarity",
    "precinctsReportingPct": 100.0,
    "counts": {
      "2020-11-03_GA_G_P_bacon_donald_j_trump_i_rep": 4018,
      "2020-11-03_GA_G_P_bacon_joseph_r_biden_dem": 625,
      "2020-11-03_GA_G_P_bacon_jo_jorgensen_lib": 25
    },
    "office": "P",
    "lastUpdated": "2020-11-05T16:39:44Z",
    "subunits": {
      "bacon_douglas": {
        "id": "bacon_douglas",
        "counts": {
          "2020-11-03_GA_G_P_bacon_donald_j_trump_i_rep": 4018,
          "2020-11-03_GA_G_P_bacon_joseph_r_biden_dem": 625,
          "2020-11-03_GA_G_P_bacon_jo_jorgensen_lib": 25
        },
        // ...
        "precinctsReportingPct": 100,
        "expectedVotes": 4668
      }
    }
  }
}
```

### CODE REVIEW

**Comment by lennybronner** [comment]
why does the test use a fixture and not an actual page? also, can we add a unit test for this?

**Comment by chriszs** [comment]
@lennybronner No particular reason, it's just better to use a fixture than have your test hit a live API. Yes, we can add a unit test using that same fixture.

**Comment by chriszs** [comment]
Unit test added.

**Comment by lennybronner** [comment]
Why does expected votes go away when we override?

**Review by lennybronner — APPROVED** [review]

**Comment by chriszs** [comment]
@lennybronner Expected votes only appears when the precinct is fully reporting. It is set to the turnout. Don't ask me why, I didn't write it.

**Pull request merged**
